version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./cofnig/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
    scale: 2
    restart: always

networks:
  default:
    driver: bridge
